[package]
name = "dsc"
version = "3.1.0-preview.1"
edition = "2021"

[profile.release]
strip = true
# optimize for size
opt-level = 2
# enable link time optimization to remove dead code
lto = true

[dependencies]
clap = { version = "4.5", features = ["derive"] }
clap_complete = { version = "4.5" }
crossterm = { version = "0.28" }
ctrlc = { version = "3.4" }
dsc_lib = { path = "../dsc_lib" }
indicatif = { version = "0.17" }
jsonschema = { version = "0.23", default-features = false }
path-absolutize = { version = "3.1" }
# reqwest = { version = "0.12.8", features = ["native-tls"], default-features = false }
schemars = { version = "0.8" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
serde_yaml = { version = "0.9" }
syntect = { version = "5.0", features = ["default-fancy"], default-features = false }
sysinfo = { version = "0.32" }
thiserror = "1.0"
tokio = { version = "1.41", features = ["io-std"] }
tracing = { version = "0.1.37" }
tracing-subscriber = { version = "0.3", features = ["ansi", "env-filter", "json"] }
tracing-indicatif = { version = "0.3" }
