name: DSC-Unofficial-$(Build.BuildId)
trigger: none

pr:
  branches:
    include:
    - unofficial-pipeline
    - release/v*

extends:
  template: ./DSC-Common.yml
  parameters:
    OfficialBuild: false
